# config/database.yml
development:
  adapter: postgresql
  encoding: unicode
  database: easybacklog_development
  pool: 5
  username: <%= ENV['DATABASE_URL'] ? '' : 'postgres' %>
  password: <%= ENV['DATABASE_URL'] ? '' : 'password' %>
  host: <%= ENV['DATABASE_URL'] ? '' : 'db' %>
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: easybacklog_test
  pool: 5
  username: postgres
  password: password
  host: db