# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  <% if ENV['DATABASE_URL'] && !ENV['DATABASE_URL'].empty? %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  <% end %>

development:
  <<: *default
  database: easybacklog_development

test:
  <<: *default
  database: easybacklog_test